export const CLOSE_LANDING_MODAL = 'CLOSE_LANDING_MODAL';
export const CLOSE_LANDING_ERROR = 'CLOSE_LANDING_ERROR';
export const LANDING_IS_LOADED = 'LANDING_IS_LOADED';
export const EMAIL_SUBMISSION_FAILURE = 'EMAIL_SUBMISSION_FAILURE';
export const EMAIL_SUBMISSION_SUCCESS = 'EMAIL_SUBMISSION_SUCCESS';
export const EMAIL_SUBMISSION_INITIATION = 'EMAIL_SUBMISSION_INITIATION';
