export const SUBMIT_EMAIL_INITIATION = 'SUBMIT_EMAIL_INITIATION';
export const SUBMIT_EMAIL_SUCCESS = 'SUBMIT_EMAIL_SUCCESS';
export const SUBMIT_EMAIL_FAILURE = 'SUBMIT_EMAIL_FAILURE';
export const CLOSE_LANDING_MODAL = 'CLOSE_LANDING_MODAL';
export const CLOSE_LANDING_ERROR = 'CLOSE_LANDING_ERROR';
export const LANDING_IS_LOADED = 'LANDING_IS_LOADED';
